### PR TITLE
[WIP] Test fix (try to figure out the duplicate bug)

### PR DESCRIPTION
**Pull request by idocx**

### CODE REVIEW

**Comment by idocx** [comment]
@hrushikesh-s I have fixed the duplicated device test in the github action. However, it seems we have some threads not exiting properly in the linux system. I have added a timeout to the github action so that it will not run for too long... It should be an issue specific to Linux since it does not appear on my side. Let me know if you have any thoughts on it :-)

**Comment by hrushikesh-s** [comment]
@idocx, thanks for fixing the duplicated device test. 
However, I'm still confused about why the CI tests for this PR are still failing. Shouldn't the CI tests all pass for this PR?

**Comment by idocx** [comment]
> @idocx, thanks for fixing the duplicated device test. However, I'm still confused about why the CI tests for this PR are still failing. Shouldn't the CI tests all pass for this PR?

I think that is the next step of fixing the CI. Some APIs have changed but the tests are still using old APIs.

**Comment by hrushikesh-s** [comment]
Ohh cool. In that case, can you pls merge this PR so that I can pull the changes to my local repo and see if that fixes the failing tests error that I'm getting in #37 ?

**Comment by idocx** [comment]
Sure! Merging now.

> Ohh cool. In that case, can you pls merge this PR so that I can pull the changes to my local repo and see if that fixes the failing tests error that I'm getting in #37 ?

**Pull request merged**
